# Dark status-bar theme.
set -g status-style bg=#222222,fg=#808080
set -g status-left-style bg=#222222,fg=#808080
set -g status-right-style bg=#222222,fg=#808080
set -g window-status-style bg=default,fg=#808080
set -g window-status-last-style bg=default,fg=#808080
set -g window-status-current-style bg=default,fg=#ffffff
