# Light status-bar theme.
set -g status-style bg=#eeeeee,fg=#707070
set -g status-left-style bg=#eeeeee,fg=#707070
set -g status-right-style bg=#eeeeee,fg=#707070
set -g window-status-style bg=default,fg=#707070
set -g window-status-last-style bg=default,fg=#707070
set -g window-status-current-style bg=default,fg=#000000
