palette = 0=#4d4d4d
palette = 1=#ea6962
palette = 2=#a9b665
palette = 3=#d8a657
palette = 4=#7daea3
palette = 5=#d3869b
palette = 6=#89b482
palette = 7=#ebdbb2
palette = 8=#928374
palette = 9=#ea6962
palette = 10=#a9b665
palette = 11=#d8a657
palette = 12=#7daea3
palette = 13=#d3869b
palette = 14=#89b482
palette = 15=#ebdbb2
background = #202020
foreground = #ebdbb2
cursor-color = #ebdbb2
cursor-text = #202020
selection-background = #4d4d4d
selection-foreground = #ebdbb2